name: Sync to Hugging Face hub

on:
  push:
    branches: [main]

  # To run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      # Step 2: Add Hugging Face as a remote and fetch changes
      - name: Add Hugging Face remote
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add huggingface https://Swathi97:$HF_TOKEN@huggingface.co/spaces/Swathi97/Smart_Search_Bot_LLM
          git fetch huggingface main

      # Step 3: Force push to overwrite the remote repository
      - name: Force push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push https://Swathi97:$HF_TOKEN@huggingface.co/spaces/Swathi97/Smart_Search_Bot_LLM main --force
